# fly.toml app configuration file generated for kk4gq-qsochat on 2023-08-28T10:58:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kk4gq-qsochat"
primary_region = "atl"

[build]

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
