# fly.toml app configuration file generated for kk4gq-couchdb on 2023-08-28T10:52:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kk4gq-couchdb"
primary_region = "atl"

[build]
  image = "couchdb:2.3.1"

[http_service]
  internal_port = 5984
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
